#!/bin/bash
echo "please login your dockerhub account."
echo "The time to pull images takes about half a day."
docker pull adminer:fastcgi
docker pull adminer:latest
docker pull aerospike:ce-5.7.0.11
docker pull amazonlinux:latest
docker pull arangodb:latest
docker pull backdrop:latest
docker pull bash:latest
docker pull bash:rc-alpine3.15
docker pull bonita:7.12.1
docker pull bonita:latest
docker pull buildpack-deps:jammy-curl
docker pull cassandra:3.11.12
docker pull cassandra:latest
docker pull celery:4
docker pull celery:latest
docker pull centos:centos7.9.2009
docker pull centos:latest
docker pull chronograf:1.8.10
docker pull chronograf:latest
docker pull cirros:0.5.1
docker pull cirros:latest
docker pull clearlinux:latest
docker pull composer:2.3.0-RC1
docker pull composer:latest
docker pull consul:1.9.16
docker pull consul:latest
docker pull convertigo:7.9.7
docker pull convertigo:latest
docker pull couchbase:enterprise-6.0.5
docker pull couchdb:3.1.2
docker pull couchdb:latest
docker pull crate:4.6.8
docker pull crate:latest
docker pull crux:3.2
docker pull crux:latest
docker pull debian:unstable-20220316
docker pull django:latest
docker pull django:onbuild
docker pull docker:git
docker pull docker:latest
docker pull drupal:7.89-php7.4-fpm-bullseye
docker pull eclipse-mosquitto:latest
docker pull eclipse-mosquitto:openssl
docker pull eggdrop:1.9.1
docker pull eggdrop:latest
docker pull elixir:latest
docker pull erlang:25.0-rc1.0.0
docker pull euleros:2.3.1806
docker pull euleros:latest
docker pull fedora:latest
docker pull flink:latest
docker pull flink:scala_2.12-java11
docker pull fsharp:10.7.0
docker pull fsharp:latest
docker pull gazebo:latest
docker pull gcc:9.4.0-buster
docker pull gcc:latest
docker pull geonetwork:3.12.3-postgres
docker pull geonetwork:latest
docker pull ghost:alpine
docker pull ghost:latest
docker pull glassfish:latest
docker pull golang:latest
docker pull golang:stretch
docker pull gradle:jdk8
docker pull gradle:latest
docker pull groovy:jdk8
docker pull groovy:latest
docker pull haproxy:latest
docker pull haproxy:lts-bullseye
docker pull haskell:9.0.2-slim-buster
docker pull haxe:4.2.4-buster
docker pull haxe:latest
docker pull hipache:latest
docker pull httpd:alpine3.15
docker pull httpd:latest
docker pull hylang:1.0a4-python3.7-alpine3.14
docker pull ibmjava:latest
docker pull ibmjava:sfj
docker pull influxdb:1.8.10
docker pull influxdb:latest
docker pull iojs:latest
docker pull iojs:onbuild
docker pull irssi:1.2.1-alpine
docker pull irssi:latest
docker pull jetty:9.4-jre8
docker pull jetty:latest
docker pull joomla:latest
docker pull joomla:php8.1-fpm
docker pull jruby:9.3.3.0-jre11
docker pull jruby:latest
docker pull julia:bullseye
docker pull julia:latest
docker pull kaazing-gateway:latest
docker pull kapacitor:1.5.9
docker pull kapacitor:latest
docker pull known:latest
docker pull kong:latest
docker pull kong:ubuntu
docker pull lightstreamer:7.2.2-jdk8-openjdk
docker pull lightstreamer:latest
docker pull mageia:cauldron
docker pull mageia:latest
docker pull mariadb:10.8.2-rc-focal
docker pull mariadb:latest
docker pull maven:3.8.4-eclipse-temurin-8
docker pull mediawiki:latest
docker pull mediawiki:stable-fpm-alpine
docker pull memcached:alpine3.15
docker pull memcached:latest
docker pull mongo-express:0.54.0
docker pull mongo-express:latest
docker pull mongo:latest
docker pull mono:latest
docker pull mono:slim
docker pull mysql:latest
docker pull nats-streaming:alpine3.15
docker pull nats:alpine3.15
docker pull nats:latest
docker pull neo4j:enterprise
docker pull neo4j:latest
docker pull neurodebian:latest
docker pull neurodebian:stretch-non-free
docker pull nextcloud:stable-fpm-alpine
docker pull nginx:latest
docker pull nginx:stable-perl
docker pull node:latest
docker pull node:lts-gallium
docker pull nuxeo:LTS-2017
docker pull odoo:14.0
docker pull open-liberty:kernel-slim-java17-openj9
docker pull open-liberty:latest
docker pull openjdk:latest
docker pull orientdb:3.2.5-tp3
docker pull orientdb:latest
docker pull owncloud:9-fpm
docker pull owncloud:latest
docker pull percona:ps-8.0.26-17
docker pull perl:5.30.3-threaded-bullseye
docker pull perl:latest
docker pull photon:3.0-20220311
docker pull photon:latest
docker pull php-zendserver:2019.0
docker pull php:latest
docker pull php:zts-buster
docker pull piwik:3-fpm
docker pull piwik:latest
docker pull plone:5.2.6-python38
docker pull plone:latest
docker pull postgres:12.10-bullseye
docker pull postgres:latest
docker pull pypy:buster
docker pull pypy:latest
docker pull python:buster
docker pull python:latest
docker pull r-base:4.1.2
docker pull r-base:latest
docker pull rabbitmq:latest
docker pull rabbitmq:management
docker pull rakudo-star:2020.10-alpine
docker pull rapidoid:5.4.5
docker pull rapidoid:latest
docker pull redis:alpine3.15
docker pull redmine:alpine3.15
docker pull registry:latest
docker pull rethinkdb:centos
docker pull rethinkdb:latest
docker pull ros:noetic-ros-base-focal
docker pull ruby:buster
docker pull rust:buster
docker pull sentry:onbuild
docker pull silverpeas:6.2.1
docker pull sl:6
docker pull solr:slim
docker pull sonarqube:lts-enterprise
docker pull spiped:alpine
docker pull swift:focal
docker pull swipl:stable
docker pull teamspeak:3.13.5
docker pull telegraf:1.20.4
docker pull thrift:0.11.0
docker pull tomcat:8.5.76-jre11-temurin-focal
docker pull tomee:9.0.0-M7-webprofile
docker pull traefik:v1.7.34-alpine
docker pull ubuntu:bionic-20220315
docker pull ubuntu:latest
docker pull vault:1.8.9
docker pull websphere-liberty:kernel-java11-openj9
docker pull wordpress:php8.1-fpm-alpine
docker pull xwiki:stable-mariadb-tomcat
docker pull znc:slim
docker pull zookeeper:3.6.3
docker pull zookeeper:latest
echo "pull completed."
python main.py --use-db --load-info --plot-result
